# Generated by Django 3.1.6 on 2021-02-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('first_keyword', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.FloatField()),
                ('keyword', models.CharField(max_length=30)),
                ('star', models.IntegerField(default=0)),
                ('star_correction', models.IntegerField(default=0)),
                ('Cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cafe')),
                ('Loc', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.loc')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='Loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.loc'),
        ),
    ]
