# Generated by Django 3.1.6 on 2021-02-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='star_correction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.loc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(),
        ),
    ]
