# Generated by Django 3.1.6 on 2021-02-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210226_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.cafe'),
        ),
    ]
